# Generated by Django 3.2.7 on 2022-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(help_text='Логин должен совпадать с логином пользователей', max_length=50, verbose_name='Логин оператора')),
                ('organisation', models.CharField(max_length=50, verbose_name='Название организации')),
                ('site_organis', models.CharField(default='www.site.site', max_length=50, verbose_name='Сайт организации')),
                ('dostup', models.CharField(choices=[('1', 'Мониторинг'), ('2', 'Мониторинг + карта'), ('3', 'Управление устройствами')], max_length=25, verbose_name='Уровень доступа')),
            ],
            options={
                'ordering': ('organisation',),
            },
        ),
    ]
